- name: Add initial users
  user:
    shell: /bin/bash
    name: "{{ item }}"
    groups: wheel
    password: "{{ users_info[item].password |
        password_hash('sha512', 1000000 | random )}}"
  loop: "{{ global_admins }}"

- name: Set root password
  user:
    name: root
    password: "{{ users_info['root'].password |
        password_hash('sha512', 1000000 | random )}}"

- name: Allow admins to sudo by authorizing the wheel group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel ALL='
    line: '%wheel ALL=(ALL) ALL'
    validate: '/usr/sbin/visudo -cf %s'
