- name: Install the base system
  hosts: all
  tags: bootstrap
  pre_tasks:
    - fail:
        msg: Security check! Target is not a VM
      when: ansible_virtualization_role != "guest"
  roles:
    - role: partitioning
      tags: [partitioning]
    - role: base_packages
      tags: [base_packages]
    - role: bootloader
      tags: [bootloader]
    - role: configure
      tags: [configure]
  post_tasks:
   - name: Reboot into the system
     tags: reboot
     reboot:

- name: Configure the installed system
  hosts: all
  tags: mainconfig
  roles:
    - role: users
      tags: [users]
    - role: locale
      tags: [locale]
    - role: vboxguest
      tags: [vboxguest]
    - role: packages
      tags: [packages]
    - role: aur
      tags: [aur]
      # This role will pull xfce and xorg
    - role: xfce_user_customizations
      tags: [xfce]
  post_tasks:
    - import_role:
        name: passwordless_sudo_user
      vars:
        state: absent
    - reboot:
      tags: reboot
