- name: Install the base system
  hosts: all
  tags: bootstrap
  environment: "{{ global_proxy_env }}"
  roles:
    # These roles pull partitioning and base_packages
    - role: bootloader
      tags: [bootloader]
    - role: configure
  post_tasks:
   - name: Reboot into the system
     tags: reboot
     reboot:

- name: Configure the installed system
  hosts: all
  tags: mainconfig
  environment: "{{ global_proxy_env }}"
  roles:
    - role: users
      tags: [users]
    - role: locale
      tags: [locale]
    - role: proxy
      tags: [proxy]
    - role: vboxguest
      tags: [vboxguest]
    - role: packages
      tags: [packages]
    - role: aur
      tags: [aur]
      # This role will pull xfce and xorg
    - role: xfce_user_customizations
      tags: [xfce]
    - role: yay_user_customizations
      tags: [yay]
  post_tasks:
    - reboot:
      tags: reboot
