- name: Export proxy variables from shell profile
  template:
    src: proxy.sh.j2
    dest: /etc/profile.d/proxy.sh
  vars:
    http_proxy: "{{ global_proxy_env.http_proxy }}"
    https_proxy: "{{ global_proxy_env.https_proxy }}"
  when: global_proxy_env

- name: Pass http{,s}_proxy through sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    line: 'Defaults env_keep += "http_proxy https_proxy no_proxy"'
    validate: '/usr/sbin/visudo -cf %s'
  when: global_proxy_env

- name: Set pacman's XferCommand to curl
  ini_file:
    create: no
    path: /etc/pacman.conf
    section: options
    option: XferCommand
    value: /usr/bin/curl -L -C - -f -o %o %u
  when: global_proxy_env