- name: Partition the target system
  tags: partitioning
  block:
  - name: Create a MBR partition table and one partition
    parted:
      device: "{{ global_device_node }}"
      state: present
      label: msdos
      number: "{{ global_partition_number }}"
      flags:
        - boot
  
  - name: Format the partition
    filesystem:
      dev:  "{{ global_device_node }}{{ global_partition_number }}"
      fstype: ext4
      opts: -O ^64bit
  
  - name: Mount the root partition
    mount:
      state: mounted
      src: "{{ global_device_node }}{{ global_partition_number }}"
      path: "{{ global_mount_point }}"
      fstype: ext4
      opts: rw,relatime
