- name: Remove custom repositories definitions
  file:
    path: /etc/pacman.d/{{ item.name }}.repo
    state: absent
  loop: "{{ custom_repos_list }}"

- name: Delete repository definitions in pacman.conf
  lineinfile:
    path: /etc/pacman.conf
    regexp: "^Include = /etc/pacman.d/{{ item.name | regex_escape }}\\.repo$"
    create: no
    state: absent
  loop: "{{ custom_repos_list }}"