- name: Check state variable
  assert:
    that: state == '' or state == 'present' or state == 'absent'
    fail: The state variable should be set to either present or absent

- name: Dispatch to proper custom_repos implementation
  import_tasks: "{{ state | default('present', True) }}.yaml"