- name: Copy custom repositories definitions
  copy:
    dest: /etc/pacman.d/{{ item.name }}.repo
    content: |
      [{{ item.name }}]
      Server = {{ item.server }}
      SigLevel = {{ item.siglevel }}
  loop: "{{ custom_repos_list }}"

- name: Include repository definitions in pacman.conf
  lineinfile:
    path: /etc/pacman.conf
    regexp: "^Include = /etc/pacman.d/{{ item.name }}\\.repo$"
    line: Include = /etc/pacman.d/{{ item.name }}.repo
    create: no
    state: present
    insertbefore: ^[[]core[]]$
  loop: "{{ custom_repos_list }}"