- name: Install themes for XFCE
  import_role:
    name: packages
  vars:
    packages:  "{{ xfce_user_customization_packages }}"

- name: Copy xfce's xinitrc to user home
  become: yes
  become_user: "{{ item }}"
  copy:
    src: xinitrc
    dest: /home/{{ item }}/.xinitrc
  loop: "{{ global_admins }}"

- name: Copy xfce's configuration for themes
  become: yes
  become_user: "{{ item }}"
  copy:
    src: xfconf/
    dest: /home/{{ item }}/.config/xfce4/xfconf/
  loop: "{{ global_admins }}"
