- name: Set pacman's XferCommand to curl
  ini_file:
    create: no
    path: /etc/pacman.conf
    section: options
    option: XferCommand
    value: /usr/bin/curl -L -C - -f -o %o %u
  when: global_proxy_env
