- name: Install refind
  command: refind-install

- name: Get root's UUID
  command: lsblk -n -o UUID {{ global_device_node }}{{ global_partition_number }}
  register: uuid
  changed_when: false

- name: Copy refind configuration
  vars:
    root_uuid: "{{ uuid.stdout }}"
  template:
    src: refind.conf.j2
    dest: "{{ global_mount_point }}/boot/refind.conf"
